{
  "name": "handsome-exception",
  "version": "1.1.2",
  "description": "exceptions handler for error when chained calling from object",
  "main": "index.js",
  "typings": "index.d.ts",
  "scripts": {
    "test": "node test.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/HandsomeWalker/handsome-exception.git"
  },
  "keywords": [
    "exception",
    "object",
    "error",
    "handler"
  ],
  "author": "dreamcreativehub@gmail.com",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/HandsomeWalker/handsome-exception/issues"
  },
  "homepage": "https://github.com/HandsomeWalker/handsome-exception#readme"
}
